### ISSUE TITLE
API error when starting price server

### ISSUE THREAD

**Issue by tmlbl** [santegoeds/oanda#3]
This may be a problem with the Oanda API itself, or due to the fact that trading is halted right now.

I am getting the following error when trying to call ConnectAndHandle on a price server, on both practice and live environment. It is unclear to me exactly which request it is in response to so I have included the whole stack trace below:

````
panic: ApiError{Code: 4, Message: The access token provided does not allow this request to be made, Moreinfo: http://developer.oanda.com/docs/v1/auth/#overview}

goroutine 1 [running]:
bitbucket.org/tm-lbl/candles.(*CandleTrader).Start(0xc82039c820, 0x43dd18, 0xc8205e25a0)
	/Users/tim/go/src/bitbucket.org/tm-lbl/candles/livetrader.go:194 +0x6e8
main.main()
	/Users/tim/go/src/bitbucket.org/tm-lbl/candles/examples/dojis.go:32 +0x72e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 9 [IO wait]:
net.runtime_pollWait(0xc655d0, 0x72, 0xc82000a1a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820060140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820060140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200600e0, 0xc820424000, 0x8000, 0x8000, 0x0, 0xc60050, 0xc82000a1a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c040, 0xc820424000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820012f30, 0xc65708, 0xc82002c040, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82009e000, 0x43e317, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82009e000, 0xc82010c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xc6e348, 0xc82009e000, 0xc82009c058, 0xc82010c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203e2d00, 0xc82010c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8203da960)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8203da960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82009c000)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc82009c000)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 16 [chan receive]:
github.com/tmlbl/oanda.(*PriceServer).initServer.func1(0xc820392700, 0xc8201d6300)
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:209 +0x4e
created by github.com/tmlbl/oanda.(*PriceServer).initServer
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:213 +0x12e

goroutine 18 [chan receive]:
github.com/tmlbl/oanda.(*PriceServer).initServer.func1(0xc820392700, 0xc8201d6360)
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:209 +0x4e
created by github.com/tmlbl/oanda.(*PriceServer).initServer
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:213 +0x12e

goroutine 20 [runnable]:
github.com/tmlbl/oanda.(*tickChans).Instruments(0xc8203926e0, 0xc8201d6420, 0xc820026720, 0x0)
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:254
github.com/tmlbl/oanda.(*PriceServer).handleMessages(0xc8203926c0, 0xc8201d6420)
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:240 +0x241
github.com/tmlbl/oanda.(*PriceServer).(github.com/tmlbl/oanda.handleMessages)-fm(0xc8201d6420)
	/Users/tim/go/src/github.com/tmlbl/oanda/prices.go:179 +0x2a
github.com/tmlbl/oanda.StreamServer.HandleMessages(0xc82031c9b0, 0xc82031c9c0, 0xc8201d6420)
	/Users/tim/go/src/github.com/tmlbl/oanda/streaming.go:110 +0x30
github.com/tmlbl/oanda.(*StreamServer).HandleMessages(0xc82031c9a0, 0xc8201d6420)
	<autogenerated>:178 +0xa2
created by github.com/tmlbl/oanda.(*messageServer).readMessages
	/Users/tim/go/src/github.com/tmlbl/oanda/streaming.go:180 +0x174
exit status 2
````

**Comment by santegoeds** [comment]
From the error message it appears that you used an invalid "Personal Access Token" when you created the Client.

**Comment by tmlbl** [comment]
Yeah that's why I'm guessing it is a problem with the API, because I am using the correct token. I will contact support.

**Comment by santegoeds** [comment]
Hi @tmlbl - I don't know if you've fixed your problem but I just realised/noticed that I get this error if I try to execute a request for which an account needs to be selected and I forgot to do so (i.e. client.AccountId() return 0).

**Comment by tmlbl** [comment]
Yes thank you! I realized that was my problem. I thought of adding code to print a helpful warning when this happens, but couldn't see how to do that easily.
